# Generated by Django 5.1.6 on 2025-02-28 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_registration_cr_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='cr_name',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='year',
        ),
    ]
